Added test cases related to Framework Controller
WebPlatformForEmbedded/Storm-Testcases pull request #33
Opened 2020-04-10 12:59 UTC by sandeep-vedam

Following are the tests that are added in this PR : 
Framework_Controller_Activating_004.test.js 
Framework_Controller_Configuration_003.test.js 
Framework_Controller_Deactivating_004.test.js 
Framework_Controller_StartDiscovery_001.test.js 
Framework_Controller_Status_002.test.js 
Framework_Controller_Status_003.test.js 
Framework_Controller_StoreConfig_001.test.js

2020-04-11 02:47 UTC, wouterlucas requested changes

2020-04-11 02:47 UTC, wouterlucas commented on src/tests/framework/Framework_Controller_StoreConfig_001.test.js
> +      description: 'Start Discovery and validate the result',
Title needs to be updated.

2020-04-12 14:49 UTC, sandeep-vedam commented on src/tests/framework/Framework_Controller_StoreConfig_001.test.js
> +      description: 'Start Discovery and validate the result',
Updated the correct title

2020-04-29 15:54 UTC, wouterlucas approved these changes

2020-04-29 15:54 UTC, merged